# Generated by Django 3.1.6 on 2021-04-02 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subfamilias',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_avaliacao.familias', verbose_name='Familia'),
        ),
    ]
