# Generated by Django 3.1.6 on 2021-04-02 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_avaliacao', '0002_auto_20210402_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrizes',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_avaliacao.fatores', verbose_name='Fator'),
        ),
        migrations.AlterField(
            model_name='matrizes',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_avaliacao.niveis', verbose_name='Nivel'),
        ),
    ]
