# Generated by Django 3.2.1 on 2021-08-10 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_avaliacao', '0003_auto_20210402_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveis',
            name='factor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='admin_avaliacao.fatores', verbose_name='Fator'),
            preserve_default=False,
        ),
    ]
