# Generated by Django 3.2.1 on 2021-08-24 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_avaliacao', '0004_niveis_factor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familias',
            options={'verbose_name': 'Familia', 'verbose_name_plural': '      Familias de Cargo'},
        ),
        migrations.AlterModelOptions(
            name='fatores',
            options={'verbose_name': 'Fator', 'verbose_name_plural': '    Fatores de Avaliação'},
        ),
        migrations.AlterModelOptions(
            name='grades',
            options={'verbose_name': 'Grade', 'verbose_name_plural': '  Grades'},
        ),
        migrations.AlterModelOptions(
            name='matrizes',
            options={'verbose_name': 'Matriz', 'verbose_name_plural': ' Matrizes'},
        ),
        migrations.AlterModelOptions(
            name='niveis',
            options={'verbose_name': 'Nivel', 'verbose_name_plural': '   Niveis de Avaliação'},
        ),
        migrations.AlterModelOptions(
            name='subfamilias',
            options={'verbose_name': ' SubFamilia', 'verbose_name_plural': '     Sub-Familias de Cargo'},
        ),
    ]
