# Generated by Django 3.2.1 on 2021-11-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_avaliacao', '0008_auto_20211004_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatores',
            name='code',
            field=models.IntegerField(default=1, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='niveis',
            name='code',
            field=models.IntegerField(default=1, unique=True, verbose_name='Código'),
        ),
    ]
