# Generated by Django 3.2.1 on 2021-11-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_avaliacao', '0009_auto_20211116_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatores',
            name='code',
            field=models.IntegerField(default=1, verbose_name='Código'),
        ),
    ]
