# Generated by Django 3.2.1 on 2022-03-21 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_avaliacao', '0012_auto_20220127_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subfamilias',
            options={'ordering': ['family'], 'verbose_name': ' SubFamilia', 'verbose_name_plural': '     Sub-Familias de Cargo'},
        ),
        migrations.AlterField(
            model_name='subfamilias',
            name='family',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='admin_avaliacao.familias', verbose_name='Familia'),
        ),
        migrations.AlterField(
            model_name='subfamilias',
            name='name',
            field=models.CharField(max_length=255, verbose_name='SubFamília'),
        ),
    ]
