# Generated by Django 3.2.1 on 2022-03-31 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_avaliacao', '0013_auto_20220321_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familias',
            options={'verbose_name': 'Família', 'verbose_name_plural': '      Famílias de Cargo'},
        ),
        migrations.AlterModelOptions(
            name='niveis',
            options={'verbose_name': 'Fator / Nível', 'verbose_name_plural': '   Níveis de Avaliação'},
        ),
        migrations.AlterModelOptions(
            name='subfamilias',
            options={'ordering': ['family'], 'verbose_name': ' SubFamília', 'verbose_name_plural': '     SubFamílias de Cargo'},
        ),
        migrations.AlterField(
            model_name='familias',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome*'),
        ),
        migrations.AlterField(
            model_name='fatores',
            name='code',
            field=models.IntegerField(default=1, unique=True, verbose_name='Código*'),
        ),
        migrations.AlterField(
            model_name='fatores',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome*'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='average',
            field=models.IntegerField(blank=True, null=True, verbose_name='Média'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='maximum',
            field=models.IntegerField(blank=True, null=True, verbose_name='Máximo'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='minimum',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mínimo'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='number',
            field=models.IntegerField(verbose_name='Número*'),
        ),
        migrations.AlterField(
            model_name='matrizes',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_avaliacao.fatores', verbose_name='Fator*'),
        ),
        migrations.AlterField(
            model_name='matrizes',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_avaliacao.niveis', verbose_name='Nível*'),
        ),
        migrations.AlterField(
            model_name='matrizes',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome*'),
        ),
        migrations.AlterField(
            model_name='niveis',
            name='code',
            field=models.IntegerField(default=1, verbose_name='Código*'),
        ),
        migrations.AlterField(
            model_name='niveis',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_avaliacao.fatores', verbose_name='Fator*'),
        ),
        migrations.AlterField(
            model_name='niveis',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome*'),
        ),
        migrations.AlterField(
            model_name='subfamilias',
            name='family',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='admin_avaliacao.familias', verbose_name='Familia*'),
        ),
        migrations.AlterField(
            model_name='subfamilias',
            name='name',
            field=models.CharField(max_length=255, verbose_name='SubFamília*'),
        ),
    ]
