# Generated by Django 3.2.1 on 2022-09-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_avaliacao', '0014_auto_20220331_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conhecimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=1, unique=True, verbose_name='Código*')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome*')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Conhecimento',
                'verbose_name_plural': 'Conhecimentos',
            },
        ),
    ]
