# Generated by Django 3.2.1 on 2022-09-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_avaliacao', '0015_conhecimentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combinacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome*')),
                ('grade', models.TextField(blank=True, default='', max_length=1000, verbose_name='Grade')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Combinação de Fatores e Niveis',
                'verbose_name_plural': '      Combinações de Fatores e Niveis',
            },
        ),
    ]
