# Generated by Django 3.2.1 on 2022-09-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_avaliacao', '0016_combinacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinacoes',
            name='grade',
            field=models.TextField(blank=True, default='', max_length=255, verbose_name='Grade'),
        ),
    ]
