# Generated by Django 3.2.1 on 2022-10-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_avaliacao', '0017_alter_combinacoes_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinacoes',
            name='grade',
            field=models.TextField(max_length=255, verbose_name='Grade'),
        ),
    ]
