# Generated by Django 3.2.1 on 2023-04-03 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_avaliacao', '0018_alter_combinacoes_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conhecimentos',
            options={'ordering': ['name'], 'verbose_name': 'Conhecimento', 'verbose_name_plural': 'Conhecimentos'},
        ),
        migrations.AlterModelOptions(
            name='familias',
            options={'ordering': ['name'], 'verbose_name': 'Família', 'verbose_name_plural': '      Famílias de Cargo'},
        ),
        migrations.AlterModelOptions(
            name='subfamilias',
            options={'ordering': ['name'], 'verbose_name': ' SubFamília', 'verbose_name_plural': '     SubFamílias de Cargo'},
        ),
    ]
