# Generated by Django 3.1.6 on 2021-04-02 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especializacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Especializacao',
                'verbose_name_plural': 'Especializacoes',
            },
        ),
        migrations.CreateModel(
            name='Experiencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
            },
        ),
        migrations.CreateModel(
            name='Descricoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nome')),
                ('cbo', models.CharField(blank=True, default='', max_length=255, verbose_name='CBO')),
                ('summary', models.CharField(blank=True, default='', max_length=255, verbose_name='Sumario')),
                ('responsibility', models.CharField(blank=True, default='', max_length=255, verbose_name='Responsabilidades')),
                ('area_specialization', models.CharField(blank=True, default='', max_length=255, verbose_name='Area Especializacao')),
                ('areas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.areas', verbose_name='Area')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.experiencias', verbose_name='Experiencia')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.formacao', verbose_name='Formacao')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.habilitacoes', verbose_name='Habilitacao')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.especializacoes', verbose_name='Especializacoes')),
            ],
            options={
                'verbose_name': 'Descricao',
                'verbose_name_plural': 'Descricoes',
            },
        ),
    ]
