# Generated by Django 3.1.6 on 2021-04-02 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0002_descricoes_especializacoes_experiencias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descricoes',
            options={'verbose_name': ' Modelo de Descricao', 'verbose_name_plural': 'Modelo de Descricoes'},
        ),
    ]
