# Generated by Django 3.2.1 on 2021-07-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0003_auto_20210402_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='descricoes',
            name='summary_coverage',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Abrangência do Cargo'),
        ),
        migrations.AddField(
            model_name='descricoes',
            name='summary_goal',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Objetivo do Cargo'),
        ),
    ]
