# Generated by Django 3.2.1 on 2021-08-24 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0004_auto_20210708_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descricoes',
            options={'verbose_name': ' Modelo de Descriçãoo', 'verbose_name_plural': 'Modelo de Descrições'},
        ),
        migrations.AlterModelOptions(
            name='formacao',
            options={'verbose_name': 'Formação', 'verbose_name_plural': 'Formações'},
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='area_specialization',
            field=models.CharField(default='', max_length=255, verbose_name='Área de Especialização'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='areas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.areas', verbose_name='Área de Formação'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='cbo',
            field=models.CharField(default='', max_length=255, verbose_name='CBO'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.experiencias', verbose_name='Experiência'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.formacao', verbose_name='Formação'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.habilitacoes', verbose_name='Habilitação'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='responsibility',
            field=models.CharField(default='', max_length=255, verbose_name='Responsabilidades'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.especializacoes', verbose_name='Especializações'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='summary',
            field=models.CharField(default='', max_length=255, verbose_name='Sumário do Cargo'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='summary_coverage',
            field=models.CharField(default='', max_length=255, verbose_name='Abrangência do Cargo'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='summary_goal',
            field=models.CharField(default='', max_length=255, verbose_name='Objetivo do Cargo'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título do Cargo'),
        ),
    ]
