# Generated by Django 3.2.1 on 2022-01-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0010_auto_20220126_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricoes',
            name='cbo',
            field=models.TextField(default='', max_length=1000, verbose_name='CBO'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='responsibility',
            field=models.TextField(default='', max_length=1000, verbose_name='Principais Responsabilidades'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='summary',
            field=models.TextField(default='', max_length=1000, verbose_name='Sumário do Cargo'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='summary_coverage',
            field=models.TextField(default='', max_length=1000, verbose_name='Abrangência do Cargo'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='summary_goal',
            field=models.TextField(default='', max_length=1000, verbose_name='Objetivo do Cargo'),
        ),
    ]
