# Generated by Django 3.2.1 on 2022-01-27 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0013_auto_20220126_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricoes',
            name='cbo',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='CBO'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.habilitacoes', verbose_name='Habilitação/Certificação Obrigatória'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.especializacoes', verbose_name='Especializações'),
        ),
    ]
