# Generated by Django 3.2.1 on 2022-02-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0014_auto_20220127_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerencia',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Nome'),
        ),
    ]
