# Generated by Django 3.2.1 on 2022-03-21 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0016_auto_20220321_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descricoes',
            name='cbo',
        ),
        migrations.RemoveField(
            model_name='descricoes',
            name='formation2',
        ),
        migrations.RemoveField(
            model_name='descricoes',
            name='formation3',
        ),
        migrations.RemoveField(
            model_name='descricoes',
            name='formation4',
        ),
        migrations.AddField(
            model_name='descricoes',
            name='areas2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Area2', to='admin_descricao.areas', verbose_name='Área de Formação 2'),
        ),
        migrations.AddField(
            model_name='descricoes',
            name='areas3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Area3', to='admin_descricao.areas', verbose_name='Área de Formação 3'),
        ),
        migrations.AddField(
            model_name='descricoes',
            name='areas4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Area4', to='admin_descricao.areas', verbose_name='Área de Formação 4'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='areas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Area', to='admin_descricao.areas', verbose_name='Área de Formação 1'),
        ),
    ]
