# Generated by Django 3.2.1 on 2022-03-21 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0017_auto_20220321_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='descricoes',
            name='qualification2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Habilitacao2', to='admin_descricao.habilitacoes', verbose_name='Habilitação/Certificação Obrigatória 2'),
        ),
        migrations.AddField(
            model_name='descricoes',
            name='qualification3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Habilitacao3', to='admin_descricao.habilitacoes', verbose_name='Habilitação/Certificação Obrigatória 3'),
        ),
        migrations.AddField(
            model_name='descricoes',
            name='qualification4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Habilitacao4', to='admin_descricao.habilitacoes', verbose_name='Habilitação/Certificação Obrigatória 4'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Habilitacao1', to='admin_descricao.habilitacoes', verbose_name='Habilitação/Certificação Obrigatória 1'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='responsibility',
            field=models.TextField(default='', max_length=1500, verbose_name='Principais Responsabilidades'),
        ),
    ]
