# Generated by Django 3.2.1 on 2022-03-28 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0018_auto_20220321_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='descricoes',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='area_specialization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Área de Especialização'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='areas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Area', to='admin_descricao.areas', verbose_name='Área de Formação 1'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.experiencias', verbose_name='Experiência'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Formacao', to='admin_descricao.formacao', verbose_name='Formação'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='responsibility',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Principais Responsabilidades'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='summary',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Sumário do Cargo'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='summary_coverage',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Abrangência do Cargo'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='summary_goal',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Objetivo do Cargo'),
        ),
    ]
