# Generated by Django 3.2.1 on 2022-03-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0019_auto_20220328_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proficiencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome*')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Proficiencia',
                'verbose_name_plural': 'Proficiencia',
            },
        ),
        migrations.AlterModelOptions(
            name='areas',
            options={'verbose_name': 'Área Formação', 'verbose_name_plural': 'Áreas de Formação'},
        ),
        migrations.AlterModelOptions(
            name='descricoes',
            options={'verbose_name': ' Modelo de Descrição', 'verbose_name_plural': 'Modelos de Descrições'},
        ),
        migrations.AlterModelOptions(
            name='experiencias',
            options={'verbose_name': 'Experiência', 'verbose_name_plural': 'Experiências'},
        ),
        migrations.AlterModelOptions(
            name='gerencia',
            options={'verbose_name': 'Gestão de Equipe', 'verbose_name_plural': 'Gestão de Equipe'},
        ),
        migrations.AlterField(
            model_name='areas',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome*'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Título do Cargo*'),
        ),
        migrations.AlterField(
            model_name='especializacoes',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome*'),
        ),
        migrations.AlterField(
            model_name='experiencias',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome*'),
        ),
        migrations.AlterField(
            model_name='formacao',
            name='code',
            field=models.IntegerField(default=1, unique=True, verbose_name='Código*'),
        ),
        migrations.AlterField(
            model_name='formacao',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome*'),
        ),
        migrations.AlterField(
            model_name='gerencia',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Nome*'),
        ),
        migrations.AlterField(
            model_name='habilitacoes',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome*'),
        ),
        migrations.AlterField(
            model_name='idiomas',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome*'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Nome*'),
        ),
    ]
