# Generated by Django 3.2.1 on 2022-04-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0020_auto_20220331_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricoes',
            name='summary',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Sumário do Cargo'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='summary_coverage',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Abrangência do Cargo'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='summary_goal',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Objetivo do Cargo'),
        ),
    ]
