# Generated by Django 3.2.1 on 2022-04-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0021_auto_20220412_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreasEspecializacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome*')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Area de Formação Complementar',
                'verbose_name_plural': 'Areas de Formações Complementares',
            },
        ),
    ]
