# Generated by Django 3.2.1 on 2022-05-09 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0022_areasespecializacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descricoes',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='descricoes',
            name='summary_coverage',
        ),
    ]
