# Generated by Django 3.2.1 on 2022-05-09 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_avaliacao', '0014_auto_20220331_1459'),
        ('admin_descricao', '0023_auto_20220509_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='descricoes',
            name='area_specialization2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area_specialization2', to='admin_descricao.areasespecializacoes', verbose_name='Área de Formação Complementar 2'),
        ),
        migrations.AddField(
            model_name='descricoes',
            name='area_specialization3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area_specialization3', to='admin_descricao.areasespecializacoes', verbose_name='Área de Formação Complementar 3'),
        ),
        migrations.AddField(
            model_name='descricoes',
            name='area_specialization4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area_specialization4', to='admin_descricao.areasespecializacoes', verbose_name='Área de Formação Complementar 4'),
        ),
        migrations.AddField(
            model_name='descricoes',
            name='areas_desired',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='areas_desired1', to='admin_descricao.areas', verbose_name='Area de Formação Desejada 1'),
        ),
        migrations.AddField(
            model_name='descricoes',
            name='areas_desired2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='areas_desired2', to='admin_descricao.areas', verbose_name='Area de Formação Desejada 2'),
        ),
        migrations.AddField(
            model_name='descricoes',
            name='areas_desired3',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='areas_desired3', to='admin_descricao.areas', verbose_name='Area de Formação Desejada 3'),
        ),
        migrations.AddField(
            model_name='descricoes',
            name='areas_desired4',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='areas_desired4', to='admin_descricao.areas', verbose_name='Area de Formação Desejada 3'),
        ),
        migrations.AddField(
            model_name='descricoes',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_avaliacao.familias', verbose_name='Família do Cargo'),
        ),
        migrations.AddField(
            model_name='descricoes',
            name='formation_desired',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formation_desired', to='admin_descricao.formacao', verbose_name='Grau de Escolaridade Desejável'),
        ),
        migrations.AddField(
            model_name='descricoes',
            name='sub_familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_avaliacao.subfamilias', verbose_name='SubFamília do Cargo'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='area_specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area_specialization1', to='admin_descricao.areasespecializacoes', verbose_name='Área de Formação Complementar 1'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='areas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Area1', to='admin_descricao.areas', verbose_name='Área de Formação 1'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='summary_goal',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Missão do Cargo'),
        ),
    ]
