# Generated by Django 3.2.1 on 2022-05-12 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0025_descricoes_manage_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricoes',
            name='manage_team',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gerencia1', to='admin_descricao.gerencia', verbose_name='Gestão de Equipe'),
        ),
    ]
