# Generated by Django 3.2.1 on 2023-03-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0026_alter_descricoes_manage_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areas',
            options={'ordering': ['name'], 'verbose_name': 'Área Formação', 'verbose_name_plural': 'Áreas de Formação'},
        ),
        migrations.AlterModelOptions(
            name='areasespecializacoes',
            options={'ordering': ['name'], 'verbose_name': 'Area de Formação Complementar', 'verbose_name_plural': 'Areas de Formações Complementares'},
        ),
        migrations.AlterModelOptions(
            name='especializacoes',
            options={'ordering': ['name'], 'verbose_name': 'Formação Complementar', 'verbose_name_plural': 'Formações Complementares'},
        ),
    ]
