# Generated by Django 3.2.1 on 2023-03-13 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0027_auto_20230313_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricoes',
            name='area_specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area_specialization1', to='admin_descricao.areas', verbose_name='Área de Formação Complementar 1'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='area_specialization2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area_specialization2', to='admin_descricao.areas', verbose_name='Área de Formação Complementar 2'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='area_specialization3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area_specialization3', to='admin_descricao.areas', verbose_name='Área de Formação Complementar 3'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='area_specialization4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area_specialization4', to='admin_descricao.areas', verbose_name='Área de Formação Complementar 4'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='areas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Area1', to='admin_descricao.areas', verbose_name='Área de Formação Obrigatoria 1'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='areas2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Area2', to='admin_descricao.areas', verbose_name='Área de Formação Obrigatoria 2'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='areas3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Area3', to='admin_descricao.areas', verbose_name='Área de Formação Obrigatoria 3'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='areas4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Area4', to='admin_descricao.areas', verbose_name='Área de Formação Obrigatoria 4'),
        ),
    ]
