# Generated by Django 3.2.1 on 2023-03-24 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0028_auto_20230313_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricoes',
            name='areas_desired',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='areas_desired1', to='admin_descricao.areas', verbose_name='Area de Formação Desejada 1'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='areas_desired2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='areas_desired2', to='admin_descricao.areas', verbose_name='Area de Formação Desejada 2'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='areas_desired3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='areas_desired3', to='admin_descricao.areas', verbose_name='Area de Formação Desejada 3'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='areas_desired4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='areas_desired4', to='admin_descricao.areas', verbose_name='Area de Formação Desejada 3'),
        ),
    ]
