# Generated by Django 3.2.1 on 2023-04-03 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0029_auto_20230324_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricoes',
            name='formation_desired',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formation_desired', to='admin_descricao.formacao', verbose_name='Grau de Escolaridade Desejável'),
        ),
        migrations.AlterField(
            model_name='descricoes',
            name='manage_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gerencia1', to='admin_descricao.gerencia', verbose_name='Gestão de Equipe'),
        ),
    ]
