# Generated by Django 5.0.4 on 2025-11-17 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0033_niveis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencias',
            options={'ordering': ['id'], 'verbose_name': 'Experiência', 'verbose_name_plural': 'Experiências'},
        ),
        migrations.AlterModelOptions(
            name='niveis',
            options={'ordering': ['name'], 'verbose_name': 'Niveis', 'verbose_name_plural': 'Niveis'},
        ),
    ]
