# Generated by Django 3.2.1 on 2021-07-08 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_avaliacao', '0003_auto_20210402_1145'),
        ('master', '0003_alter_area_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_descricao', '0004_auto_20210708_1547'),
        ('tenants', '0003_auto_20210708_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, unique=True, verbose_name='Nome')),
                ('cbo', models.CharField(blank=True, default='', max_length=255, verbose_name='CBO')),
                ('summary', models.CharField(blank=True, default='', max_length=255, verbose_name='Atividades do Cargo')),
                ('summary_goal', models.CharField(blank=True, default='', max_length=255, verbose_name='Objetivo do Cargo')),
                ('summary_coverage', models.CharField(blank=True, default='', max_length=255, verbose_name='Abrangência do Cargo')),
                ('responsibility', models.CharField(blank=True, default='', max_length=255, verbose_name='Responsabilidades')),
                ('area_specialization', models.CharField(blank=True, default='', max_length=255, verbose_name='Area Especializacao')),
                ('title_super', models.CharField(blank=True, default='', max_length=255, verbose_name='Cargo do Superior')),
                ('manage_team', models.CharField(blank=True, choices=[('NT', 'Não Tem'), ('GE', 'Gestor de Equipe'), ('GG', 'Gestor de Gestores')], default='', max_length=20, null=True, verbose_name='Estado')),
                ('position_team', models.CharField(blank=True, default='', max_length=255, verbose_name='Cargos da Equipe')),
                ('proficiency', models.CharField(blank=True, default='', max_length=255, verbose_name='Proficiência')),
                ('knowledge', models.CharField(blank=True, default='', max_length=255, verbose_name='Conhecimento')),
                ('information', models.CharField(blank=True, default='', max_length=255, verbose_name='Informações')),
                ('date_approval', models.DateTimeField(blank=True, verbose_name='Data de Aprovação')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Idioma')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.area', verbose_name='Area')),
                ('areas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='admin_descricao.areas', verbose_name='Area')),
                ('areas_desired', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas_desired', to='admin_descricao.areas', verbose_name='Area Desejada')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.diretoria', verbose_name='Diretoria')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.experiencias', verbose_name='Experiencia')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_avaliacao.familias', verbose_name='Familia')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formation', to='admin_descricao.formacao', verbose_name='Formacao')),
                ('formation_desired', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formation_desired', to='admin_descricao.formacao', verbose_name='Formacao Desejada')),
                ('idioma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.idiomas', verbose_name='Idioma')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.habilitacoes', verbose_name='Habilitacao')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.especializacoes', verbose_name='Especializacoes')),
                ('sub_familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_avaliacao.subfamilias', verbose_name='SubFamilia')),
                ('supervision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_avaliacao.fatores', verbose_name='Supervisao Recebida')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Descricao',
                'verbose_name_plural': 'Descricao',
            },
        ),
    ]
