# Generated by Django 3.2.1 on 2021-07-12 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_descricao', '0004_auto_20210708_1547'),
        ('descricao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricao',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Aprovador'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='areas',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='admin_descricao.areas', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='areas_desired',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='areas_desired', to='admin_descricao.areas', verbose_name='Area Desejada'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='date_approval',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='experience',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.experiencias', verbose_name='Experiencia'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='formation',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='formation', to='admin_descricao.formacao', verbose_name='Formacao'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='formation_desired',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='formation_desired', to='admin_descricao.formacao', verbose_name='Formacao Desejada'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='manage_team',
            field=models.CharField(blank=True, choices=[('NT', 'Não Tem'), ('GE', 'Gestor de Equipe'), ('GG', 'Gestor de Gestores')], default='', max_length=20, null=True, verbose_name='Gerencia'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='qualification',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.habilitacoes', verbose_name='Habilitacao'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='specialization',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.especializacoes', verbose_name='Especializacoes'),
        ),
    ]
