# Generated by Django 3.2.1 on 2021-07-12 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0004_auto_20210708_1547'),
        ('descricao', '0002_auto_20210712_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricao',
            name='areas',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='admin_descricao.areas', verbose_name='Area'),
        ),
    ]
