# Generated by Django 3.2.1 on 2021-07-12 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0004_auto_20210708_1547'),
        ('descricao', '0003_alter_descricao_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricao',
            name='area_specialization',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Area Especializacao'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='areas_desired',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='areas_desired', to='admin_descricao.areas', verbose_name='Area Desejada'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='cbo',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='CBO'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='experience',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.experiencias', verbose_name='Experiencia'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='formation',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formation', to='admin_descricao.formacao', verbose_name='Formacao'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='formation_desired',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formation_desired', to='admin_descricao.formacao', verbose_name='Formacao Desejada'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='information',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Informações'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='knowledge',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Conhecimento'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='position_team',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Cargos da Equipe'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='proficiency',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Proficiência'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='qualification',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.habilitacoes', verbose_name='Habilitacao'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='responsibility',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Responsabilidades'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='specialization',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.especializacoes', verbose_name='Especializacoes'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Atividades do Cargo'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='summary_coverage',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Abrangência do Cargo'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='summary_goal',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Objetivo do Cargo'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='title_super',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Cargo do Superior'),
        ),
    ]
