# Generated by Django 3.2.1 on 2021-07-12 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_area_name'),
        ('descricao', '0004_auto_20210712_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricao',
            name='area',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='master.area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='board',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='master.diretoria', verbose_name='Diretoria'),
        ),
    ]
