# Generated by Django 3.2.1 on 2021-07-23 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_area_name'),
        ('descricao', '0005_auto_20210712_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='descricao',
            name='status',
            field=models.CharField(blank=True, choices=[('EP', 'Em Preenchimento'), ('FN', 'Finalizado'), ('AP', 'Aprovado')], default='EP', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.diretoria', verbose_name='Diretoria'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='manage_team',
            field=models.CharField(blank=True, choices=[('Não Tem', 'Não Tem'), ('Gestor de Equipe', 'Gestor de Equipe'), ('Gestor de Gestores', 'Gestor de Gestores')], default='', max_length=20, null=True, verbose_name='Gerencia'),
        ),
    ]
