# Generated by Django 3.2.1 on 2021-07-23 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('descricao', '0006_auto_20210723_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='descricao',
            name='date_conclusion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusao'),
        ),
        migrations.AddField(
            model_name='descricao',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_id', to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approver', to=settings.AUTH_USER_MODEL, verbose_name='Aprovador'),
        ),
    ]
