# Generated by Django 3.2.1 on 2021-07-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descricao', '0007_auto_20210723_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='descricao',
            name='function',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='status',
            field=models.CharField(blank=True, choices=[('Aberto', 'Aberto'), ('Finalizado', 'Finalizado'), ('Aprovado', 'Aprovado')], default='EP', max_length=20, verbose_name='Status'),
        ),
    ]
