# Generated by Django 3.2.1 on 2021-10-27 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0008_gerencia'),
        ('descricao', '0009_alter_descricao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricao',
            name='manage_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gerencia', to='admin_descricao.gerencia', verbose_name='Gerencia'),
        ),
    ]
