# Generated by Django 3.2.1 on 2022-01-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descricao', '0011_alter_descricao_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricao',
            name='responsibility',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Responsabilidades'),
        ),
    ]
