# Generated by Django 3.2.1 on 2022-03-31 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0020_auto_20220331_1459'),
        ('descricao', '0013_auto_20220127_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricao',
            name='proficiency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.proficiencias', verbose_name='Proficiencia'),
        ),
    ]
