# Generated by Django 3.2.1 on 2022-04-12 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_auto_20220331_1459'),
        ('admin_descricao', '0020_auto_20220331_1459'),
        ('descricao', '0015_auto_20220331_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricao',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.area', verbose_name='Subárea'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.diretoria', verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='formation',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formation', to='admin_descricao.formacao', verbose_name='Formação'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='formation_desired',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formation_desired', to='admin_descricao.formacao', verbose_name='Formação Desejada'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='information',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Outras Informações'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='manage_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gerencia', to='admin_descricao.gerencia', verbose_name='Gerência'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='proficiency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.proficiencias', verbose_name='Proficiência'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='summary_coverage',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Abrangência do Cargo'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='summary_goal',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Objetivo do Cargo'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='title',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Título do Cargo'),
        ),
    ]
