# Generated by Django 3.2.1 on 2022-04-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_alter_tenant_core'),
        ('descricao', '0016_auto_20220412_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='descricao',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Título do Cargo'),
        ),
        migrations.AlterUniqueTogether(
            name='descricao',
            unique_together={('title', 'tenant_id', 'is_active')},
        ),
    ]
