# Generated by Django 3.2.1 on 2022-04-27 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0021_auto_20220412_0813'),
        ('descricao', '0018_auto_20220427_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='descricao',
            name='areas2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Area_2', to='admin_descricao.areas', verbose_name='Área de Formação 2'),
        ),
        migrations.AddField(
            model_name='descricao',
            name='areas3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Area_3', to='admin_descricao.areas', verbose_name='Área de Formação 3'),
        ),
        migrations.AddField(
            model_name='descricao',
            name='areas4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Area_4', to='admin_descricao.areas', verbose_name='Área de Formação 4'),
        ),
        migrations.AddField(
            model_name='descricao',
            name='qualification2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Habilitacao_2', to='admin_descricao.habilitacoes', verbose_name='Habilitação/Certificação Obrigatória 2'),
        ),
        migrations.AddField(
            model_name='descricao',
            name='qualification3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Habilitacao_3', to='admin_descricao.habilitacoes', verbose_name='Habilitação/Certificação Obrigatória 3'),
        ),
        migrations.AddField(
            model_name='descricao',
            name='qualification4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Habilitacao_4', to='admin_descricao.habilitacoes', verbose_name='Habilitação/Certificação Obrigatória 4'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='areas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Area_1', to='admin_descricao.areas', verbose_name='Área de Formação 1'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='formation',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formation', to='admin_descricao.formacao', verbose_name='Grau de Escolaridade Obrigatório'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='formation_desired',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formation_desired', to='admin_descricao.formacao', verbose_name='Grau de Escolaridade Desejável'),
        ),
        migrations.RemoveField(
            model_name='descricao',
            name='qualification',
        ),
        migrations.AddField(
            model_name='descricao',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Habilitacao_1', to='admin_descricao.habilitacoes', verbose_name='Habilitação/Certificação Obrigatória 1'),
        ),
    ]
