# Generated by Django 3.2.1 on 2022-04-27 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0022_areasespecializacoes'),
        ('descricao', '0019_auto_20220427_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricao',
            name='specialization',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.especializacoes', verbose_name='Formação Complementar'),
        ),
    ]
