# Generated by Django 3.2.1 on 2022-04-27 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0022_areasespecializacoes'),
        ('descricao', '0020_alter_descricao_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='descricao',
            name='area_specialization2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area_specialization_2', to='admin_descricao.areasespecializacoes', verbose_name='Área de Formação Complementar 2'),
        ),
        migrations.AddField(
            model_name='descricao',
            name='area_specialization3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area_specialization_3', to='admin_descricao.areasespecializacoes', verbose_name='Área de Formação Complementar 3'),
        ),
        migrations.AddField(
            model_name='descricao',
            name='area_specialization4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area_specialization_4', to='admin_descricao.areasespecializacoes', verbose_name='Área de Formação Complementar 4'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='area_specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area_specialization_1', to='admin_descricao.areasespecializacoes', verbose_name='Área de Formação Complementar 1'),
        ),
    ]
