# Generated by Django 3.2.1 on 2022-04-28 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0022_areasespecializacoes'),
        ('descricao', '0021_auto_20220427_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='descricao',
            name='idioma2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='idioma2', to='admin_descricao.idiomas', verbose_name='Idioma 2'),
        ),
        migrations.AddField(
            model_name='descricao',
            name='idioma3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='idioma3', to='admin_descricao.idiomas', verbose_name='Idioma 3'),
        ),
        migrations.AddField(
            model_name='descricao',
            name='proficiency2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proficiencia2', to='admin_descricao.proficiencias', verbose_name='Proficiência 2'),
        ),
        migrations.AddField(
            model_name='descricao',
            name='proficiency3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proficiencia3', to='admin_descricao.proficiencias', verbose_name='Proficiência 3'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='idioma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='idioma1', to='admin_descricao.idiomas', verbose_name='Idioma 1'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='proficiency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proficiencia1', to='admin_descricao.proficiencias', verbose_name='Proficiência 1'),
        ),
    ]
