# Generated by Django 3.2.1 on 2022-04-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descricao', '0022_auto_20220428_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricao',
            name='information',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Outras Informações'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='knowledge',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Conhecimentos Específicos'),
        ),
    ]
