# Generated by Django 3.2.1 on 2022-05-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descricao', '0024_auto_20220509_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descricao',
            name='qualification4',
        ),
    ]
