# Generated by Django 3.2.1 on 2022-05-09 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0024_auto_20220509_1217'),
        ('descricao', '0025_remove_descricao_qualification4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricao',
            name='areas_desired',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='areas_desired_1', to='admin_descricao.areas', verbose_name='Area de Formação Desejada 1'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='areas_desired2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='areas_desired_2', to='admin_descricao.areas', verbose_name='Area de Formação Desejada 2'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='areas_desired3',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='areas_desired_3', to='admin_descricao.areas', verbose_name='Area de Formação Desejada 3'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='areas_desired4',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='areas_desired_4', to='admin_descricao.areas', verbose_name='Area de Formação Desejada 3'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='formation_desired',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formation_desired1', to='admin_descricao.formacao', verbose_name='Grau de Escolaridade Desejável'),
        ),
    ]
