# Generated by Django 3.2.1 on 2022-05-12 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0026_alter_descricoes_manage_team'),
        ('descricao', '0026_auto_20220509_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricao',
            name='areas_desired4',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='areas_desired_4', to='admin_descricao.areas', verbose_name='Area de Formação Desejada 4'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='position_team',
            field=models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='Cargos da Equipe'),
        ),
    ]
