# Generated by Django 3.2.1 on 2022-05-17 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0026_alter_descricoes_manage_team'),
        ('descricao', '0027_auto_20220512_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricao',
            name='experience',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.experiencias', verbose_name='Experiencia'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='formation',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formation', to='admin_descricao.formacao', verbose_name='Grau de Escolaridade Obrigatório'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='formation_desired',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formation_desired1', to='admin_descricao.formacao', verbose_name='Grau de Escolaridade Desejável'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='position_team',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Cargos da Equipe'),
        ),
    ]
