# Generated by Django 3.2.1 on 2022-05-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descricao', '0028_auto_20220517_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricao',
            name='position_team',
            field=models.TextField(blank=True, default='', max_length=10000, null=True, verbose_name='Cargos da Equipe'),
        ),
    ]
