# Generated by Django 3.2.1 on 2022-09-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descricao', '0029_alter_descricao_position_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricao',
            name='position_team',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Cargos da Equipe'),
        ),
    ]
