# Generated by Django 3.2.1 on 2023-03-13 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0027_auto_20230313_1039'),
        ('descricao', '0030_alter_descricao_position_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricao',
            name='areas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Area_1', to='admin_descricao.areas', verbose_name='Área de Formação Obrigatória 1'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='areas2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Area_2', to='admin_descricao.areas', verbose_name='Área de Formação Obrigatória 2'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='areas3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Area_3', to='admin_descricao.areas', verbose_name='Área de Formação Obrigatória 3'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='areas4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Area_4', to='admin_descricao.areas', verbose_name='Área de Formação Obrigatória 4'),
        ),
    ]
