# Generated by Django 3.2.1 on 2023-05-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descricao', '0032_auto_20230324_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricao',
            name='information',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Outras Informações'),
        ),
        migrations.AlterField(
            model_name='descricao',
            name='knowledge',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Conhecimentos Específicos'),
        ),
    ]
