# Generated by Django 3.2.1 on 2023-05-25 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0032_alter_formacao_options'),
        ('descricao', '0033_auto_20230511_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricao',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.experiencias', verbose_name='Experiencia'),
        ),
    ]
