# Generated by Django 5.0.4 on 2024-08-06 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0032_alter_formacao_options'),
        ('descricao', '0036_alter_descricao_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricao',
            name='formation',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formation', to='admin_descricao.formacao', verbose_name='Grau de Escolaridade Mínimo'),
        ),
    ]
