# Generated by Django 5.0.4 on 2025-02-21 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0033_niveis'),
        ('admin_geral', '0012_alter_dimensao_options'),
        ('descricao', '0037_alter_descricao_formation'),
    ]

    operations = [
        migrations.AddField(
            model_name='descricao',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.niveis', verbose_name='Nivel do Cargo'),
        ),
        migrations.AddField(
            model_name='descricao',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_geral.sector', verbose_name='Setor de Atuação'),
        ),
    ]
