# Generated by Django 5.0.4 on 2025-02-24 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_geral', '0012_alter_dimensao_options'),
        ('descricao', '0038_descricao_level_descricao_setor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descricao',
            name='setor',
        ),
        migrations.AddField(
            model_name='descricao',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_geral.sector', verbose_name='Setor de Atuação'),
        ),
    ]
