# Generated by Django 5.0.4 on 2026-03-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descricao', '0039_remove_descricao_setor_descricao_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='descricao',
            name='adicional',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Adicional'),
        ),
    ]
