# Generated by Django 5.2.14 on 2026-05-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descricao', '0040_descricao_adicional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa_id', models.CharField(max_length=100, unique=True)),
                ('progresso', models.IntegerField(default=0)),
                ('status', models.CharField(default='Pendente', max_length=50)),
            ],
        ),
    ]
