# Generated by Django 3.2.1 on 2021-07-05 13:01

from django.db import migrations, models
import django.db.models.deletion
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admin_geral', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='annual_invoicing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Faturamento'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='capital',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Origem do Capital'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='city',
            field=models.CharField(default='', max_length=40, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='cnpj',
            field=django_cpf_cnpj.fields.CNPJField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='complement',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='employees',
            field=models.IntegerField(blank=True, null=True, verbose_name='Empregados'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='number',
            field=models.CharField(default='', max_length=4, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='outsource',
            field=models.IntegerField(blank=True, null=True, verbose_name='Terceirizados'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(default='', max_length=19, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_geral.sector', verbose_name='Setor de Atuação'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='states',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia '), ('CE', 'Ceará'), ('DF', 'Distrito Federal '), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='', max_length=15, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='type',
            field=models.CharField(choices=[('PB', 'Publica'), ('PV', 'Privada')], default='', max_length=15, null=True, verbose_name='Tipo de Empresa'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Nome'),
        ),
    ]
