# Generated by Django 3.2.1 on 2021-09-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_auto_20210708_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterField(
            model_name='tenant',
            name='employees',
            field=models.IntegerField(blank=True, null=True, verbose_name='Colaboradores Próprios'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='outsource',
            field=models.IntegerField(blank=True, null=True, verbose_name='Colaboradores Terceirizados'),
        ),
    ]
