''# Generated by Django 3.2.1 on 2021-10-27 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_geral', '0005_auto_20211027_1241'),
        ('tenants', '0004_auto_20210915_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='annual_invoicing',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='capital',
        ),
        migrations.AddField(
            model_name='tenant',
            name='governanca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_geral.governanca', verbose_name='Governança'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_geral.origemcapital', verbose_name='Origem de Capital'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_geral.dimensao', verbose_name='Dimensão'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_geral.tipoempresa', verbose_name='Tipo de Empresa'),
        ),
    ]
