# Generated by Django 3.2.1 on 2022-03-21 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_geral', '0005_auto_20211027_1241'),
        ('tenants', '0006_auto_20211027_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_geral.dimensao', verbose_name='Dimensão Anual'),
        ),
    ]
