# Generated by Django 3.2.1 on 2022-03-28 22:06

from django.db import migrations, models
import django.db.models.deletion
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admin_geral', '0006_auto_20220328_1906'),
        ('tenants', '0007_alter_tenant_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='address',
            field=models.CharField(default='', max_length=150, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='city',
            field=models.CharField(default='', max_length=40, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='cnpj',
            field=django_cpf_cnpj.fields.CNPJField(default='', max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='admin_geral.tipoempresa', verbose_name='Constituição do Capital'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='employees',
            field=models.IntegerField(default=0, verbose_name='Colaboradores Próprios'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='governanca',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='admin_geral.governanca', verbose_name='Governança'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Nome da Empresa'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='number',
            field=models.CharField(default='', max_length=4, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='origin',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='admin_geral.origemcapital', verbose_name='Origem de Capital'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='outsource',
            field=models.IntegerField(default=0, verbose_name='Colaboradores Terceirizados'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(default='', max_length=19, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='sector',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='admin_geral.sector', verbose_name='Setor de Atuação'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='size',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='admin_geral.dimensao', verbose_name='Dimensão Financeira Anual'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='states',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia '), ('CE', 'Ceará'), ('DF', 'Distrito Federal '), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='', max_length=15, verbose_name='Estado'),
        ),
    ]
