# Generated by Django 3.2.1 on 2022-03-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_auto_20220328_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='employees',
            field=models.IntegerField(verbose_name='Colaboradores Próprios'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='outsource',
            field=models.IntegerField(verbose_name='Colaboradores Terceirizados'),
        ),
    ]
