# Generated by Django 3.2.1 on 2022-03-28 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_geral', '0007_core'),
        ('tenants', '0013_tenant_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='core',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_geral.core', verbose_name='Core da Empresa'),
        ),
    ]
