# Generated by Django 3.2.1 on 2022-03-31 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_geral', '0008_auto_20220331_1459'),
        ('tenants', '0014_alter_tenant_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='core',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_geral.core', verbose_name='Processos Core da Empresa'),
        ),
    ]
