# Generated by Django 3.2.1 on 2023-03-13 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_geral', '0009_alter_dimensao_options'),
        ('tenants', '0015_alter_tenant_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='size',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='admin_geral.dimensao', verbose_name='Faturamento Bruto'),
        ),
    ]
