# Generated by Django 5.0.4 on 2026-04-14 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_geral', '0013_plans_value_aval_alter_plans_value'),
        ('tenants', '0017_alter_tenant_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='plano',
            field=models.ForeignKey( null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_geral.plans', verbose_name='Plano'),
        ),
    ]
