# Generated by Django 5.0.4 on 2026-04-28 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_geral', '0014_plansavaliacao_remove_plans_value_aval'),
        ('tenants', '0018_remove_tenant_core_tenant_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='planoaval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_geral.plansavaliacao', verbose_name='Plano Avaliação'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='plano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_geral.plans', verbose_name='Plano Descrição'),
        ),
    ]
