# Generated by Django 3.2.1 on 2021-06-23 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True, verbose_name='Nome')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.diretoria', verbose_name='Diretoria')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Area da Diretoria',
                'verbose_name_plural': 'Area da Diretoria',
            },
        ),
    ]
