# Generated by Django 3.2.1 on 2021-07-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Area'),
        ),
    ]
