# Generated by Django 3.2.1 on 2021-09-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20210825_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Area da Diretoria', 'verbose_name_plural': 'Areas da Diretoria'},
        ),
        migrations.AlterModelOptions(
            name='diretoria',
            options={'verbose_name': 'Diretoria', 'verbose_name_plural': 'Diretorias'},
        ),
    ]
