# Generated by Django 3.2.1 on 2022-03-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_alter_tenant_core'),
        ('master', '0005_auto_20210915_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diretoria',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterUniqueTogether(
            name='diretoria',
            unique_together={('name', 'tenant_id')},
        ),
    ]
