# Generated by Django 3.2.1 on 2022-03-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_alter_tenant_core'),
        ('master', '0006_auto_20220328_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Area'),
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('name', 'tenant_id')},
        ),
    ]
