# Generated by Django 3.2.1 on 2023-11-14 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_auto_20220331_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['name'], 'verbose_name': 'Subárea da Empresa', 'verbose_name_plural': 'Subáreas da Empresa'},
        ),
        migrations.AlterModelOptions(
            name='diretoria',
            options={'ordering': ['name'], 'verbose_name': 'Area da Empresa', 'verbose_name_plural': 'Áreas da Empresa'},
        ),
    ]
