# Generated by Django 5.0.4 on 2025-11-17 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_auto_20231113_2334'),
        ('tenants', '0017_alter_tenant_states'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('name', 'board', 'tenant')},
        ),
    ]
