# Generated by Django 3.1.6 on 2021-04-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(default='1900-01-01',verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(default='', max_length=40, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='person',
            name='civil_status',
            field=models.CharField(choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viúvo', 'Viúvo')], default='', max_length=10, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='person',
            name='complement',
            field=models.CharField(default='', max_length=200, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='person',
            name='cpf',
            field=models.CharField(default='', max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='person',
            name='number',
            field=models.PositiveIntegerField(default=0, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(default='', max_length=19, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], default='', max_length=10, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='person',
            name='states',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia '), ('CE', 'Ceará'), ('DF', 'Distrito Federal '), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Nome'),
        ),
    ]
