# Generated by Django 3.1.6 on 2021-04-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20210429_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(default='', max_length=150, verbose_name='Endereço'),
        ),
    ]
