# Generated by Django 3.2.1 on 2021-06-19 22:41

import cpf_field.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('person', '0004_auto_20210505_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='complement',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, unique=True, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='person',
            name='number',
            field=models.CharField(default='', max_length=4, verbose_name='Número'),
        ),
    ]
