# Generated by Django 3.2.1 on 2021-06-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('user_account', '0003_customuser_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tenants',
            field=models.ManyToManyField(to='tenants.Tenant'),
        ),
    ]
