# Generated by Django 3.2.1 on 2021-06-20 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('user_account', '0004_customuser_tenants'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='default_tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='default_tenant', to='tenants.tenant'),
            preserve_default=False,
        ),
    ]
