# Generated by Django 3.2.1 on 2021-07-05 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_auto_20210705_1001'),
        ('user_account', '0012_alter_customuser_default_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='default_tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='default_tenant', to='tenants.tenant', verbose_name='Empresa'),
        ),
    ]
