# Generated by Django 3.2.1 on 2021-08-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0014_customuser_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='kind',
            field=models.CharField(choices=[('M', 'Master'), ('C', 'Comum')], default='C', max_length=20, verbose_name='Tipo de Usuário'),
        ),
    ]
