# Generated by Django 3.2.1 on 2022-09-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0015_alter_customuser_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='kind',
            field=models.CharField(choices=[('Master', 'Master'), ('Comum', 'Comum')], default='C', max_length=20, verbose_name='Tipo de Usuário'),
        ),
    ]
