# Generated by Django 3.2.1 on 2021-11-18 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0009_formacao_code'),
        ('admin_avaliacao', '0011_auto_20211116_1108'),
        ('avaliacao', '0003_auto_20211116_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='grade',
            field=models.IntegerField(default=0, verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='point',
            field=models.IntegerField(default=0, verbose_name='Pontos'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='ceo',
            field=models.BooleanField(default='false', null=True, verbose_name='1º Executivo'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='level1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='level1', to='admin_avaliacao.niveis', verbose_name='Níveis'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='level2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='level2', to='admin_avaliacao.niveis', verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='level3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='level3', to='admin_avaliacao.niveis', verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='level4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='level4', to='admin_avaliacao.niveis', verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='level5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='level5', to='admin_avaliacao.niveis', verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='level6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='level6', to='admin_avaliacao.niveis', verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='level7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='level7', to='admin_avaliacao.niveis', verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='level8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='level8', to='admin_avaliacao.niveis', verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='manage_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.gerencia', verbose_name='Gerencia'),
        ),
    ]
