# Generated by Django 3.2.1 on 2022-01-21 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_auto_20211027_2024'),
        ('avaliacao', '0006_alter_avaliacao_title_super'),
    ]

    operations = [
        migrations.CreateModel(
            name='Superior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, unique=True, verbose_name='Nome')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Superior',
                'verbose_name_plural': 'Superior',
            },
        ),
    ]
