# Generated by Django 3.2.1 on 2022-01-21 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0007_superior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='title_super',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='avaliacao.superior', verbose_name='Superior'),
        ),
    ]
