# Generated by Django 3.2.1 on 2022-05-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0009_auto_20220321_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='ceo',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='1º Executivo'),
        ),
    ]
