# Generated by Django 3.2.1 on 2022-05-18 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_auto_20220331_1459'),
        ('avaliacao', '0011_alter_avaliacao_ceo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.area', verbose_name='Subárea'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master.diretoria', verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='ceo',
            field=models.BooleanField(default=False, verbose_name='1º Executivo'),
        ),
    ]
