# Generated by Django 3.2.1 on 2022-09-29 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0026_alter_descricoes_manage_team'),
        ('avaliacao', '0013_superior_evaluation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='manage_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.gerencia', verbose_name='Gestão de Equipe'),
        ),
    ]
