# Generated by Django 3.2.1 on 2022-10-17 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_avaliacao', '0018_alter_combinacoes_grade'),
        ('avaliacao', '0016_alter_avaliacao_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Grade', to='admin_avaliacao.combinacoes', verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='point',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pontos'),
        ),
    ]
