# Generated by Django 3.2.1 on 2023-11-14 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_avaliacao', '0019_auto_20230403_1905'),
        ('avaliacao', '0017_auto_20221017_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='factor1',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='factor1', to='admin_avaliacao.fatores', verbose_name='Fatores de Avaliação'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='factor2',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.PROTECT, related_name='factor2', to='admin_avaliacao.fatores', verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='factor3',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.PROTECT, related_name='factor3', to='admin_avaliacao.fatores', verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='factor4',
            field=models.ForeignKey(blank=True, default=4, on_delete=django.db.models.deletion.PROTECT, related_name='factor4', to='admin_avaliacao.fatores', verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='factor5',
            field=models.ForeignKey(blank=True, default=5, on_delete=django.db.models.deletion.PROTECT, related_name='factor5', to='admin_avaliacao.fatores', verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='factor6',
            field=models.ForeignKey(blank=True, default=6, on_delete=django.db.models.deletion.PROTECT, related_name='factor6', to='admin_avaliacao.fatores', verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='factor7',
            field=models.ForeignKey(blank=True, default=7, on_delete=django.db.models.deletion.PROTECT, related_name='factor7', to='admin_avaliacao.fatores', verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='factor8',
            field=models.ForeignKey(blank=True, default=8, on_delete=django.db.models.deletion.PROTECT, related_name='factor8', to='admin_avaliacao.fatores', verbose_name=' '),
        ),
    ]
