# Generated by Django 3.2.1 on 2024-01-17 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_auto_20231113_2334'),
        ('avaliacao', '0018_auto_20231113_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.area', verbose_name='Subárea'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.diretoria', verbose_name='Área'),
        ),
    ]
