# Generated by Django 3.2.1 on 2024-02-16 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_descricao', '0032_alter_formacao_options'),
        ('avaliacao', '0019_auto_20240117_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='manage_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_descricao.gerencia', verbose_name='Gestão de Equipe'),
        ),
    ]
