# Generated by Django 3.2.1 on 2024-03-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0020_alter_avaliacao_manage_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='description',
            field=models.IntegerField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
