# Generated by Django 5.0.4 on 2024-04-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0021_avaliacao_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Título do Cargo'),
        ),
    ]
