# Generated by Django 5.0.4 on 2024-08-06 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_avaliacao', '0019_auto_20230403_1905'),
        ('avaliacao', '0024_alter_superior_title_alter_superior_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Grade', to='admin_avaliacao.combinacoes', verbose_name='Grade'),
        ),
    ]
