# Generated by Django 3.1.6 on 2021-04-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('detail', models.CharField(blank=True, default='', max_length=255, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor')),
                ('discount', models.CharField(blank=True, default='', max_length=255, verbose_name='Cupom')),
                ('percent', models.IntegerField(blank=True, default=0, null=True, verbose_name='Percentual')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('detail', models.CharField(blank=True, default='', max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
            },
        ),
    ]
