# Generated by Django 3.2.1 on 2021-10-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_geral', '0003_nivelcargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimensao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Dimensão',
                'verbose_name_plural': 'Dimensões',
            },
        ),
        migrations.CreateModel(
            name='Governanca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Governança',
                'verbose_name_plural': 'Governanças',
            },
        ),
        migrations.CreateModel(
            name='Origemcapital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Origem do Capital',
                'verbose_name_plural': 'Origens do Capital',
            },
        ),
        migrations.CreateModel(
            name='Tipoempresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de Empresa',
                'verbose_name_plural': 'Tipos de Empresa',
            },
        ),
    ]
