# Generated by Django 3.2.1 on 2021-10-27 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_geral', '0004_dimensao_governanca_origemcapital_tipoempresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='origemcapital',
            options={'verbose_name': 'Origem do Capital', 'verbose_name_plural': ' Origens do Capital'},
        ),
        migrations.AlterModelOptions(
            name='tipoempresa',
            options={'verbose_name': 'Tipo de Empresa', 'verbose_name_plural': '  Tipos de Empresa'},
        ),
    ]
