# Generated by Django 3.2.1 on 2022-03-28 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_geral', '0005_auto_20211027_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimensao',
            options={'verbose_name': 'Dimensão Financeira', 'verbose_name_plural': 'Dimensões Financeiras'},
        ),
        migrations.AlterModelOptions(
            name='tipoempresa',
            options={'verbose_name': 'Constituição do Capital', 'verbose_name_plural': '  Constituição do Capital'},
        ),
    ]
