# Generated by Django 3.2.1 on 2022-03-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_geral', '0006_auto_20220328_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Core da Empresa',
                'verbose_name_plural': 'Core da Empresa',
            },
        ),
    ]
