# Generated by Django 3.2.1 on 2022-03-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_geral', '0007_core'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='core',
            options={'verbose_name': 'Processo Core da Empresa', 'verbose_name_plural': 'Processos Core da Empresa'},
        ),
        migrations.AlterModelOptions(
            name='governanca',
            options={'verbose_name': 'Governança', 'verbose_name_plural': 'Governança'},
        ),
        migrations.AlterModelOptions(
            name='nivelcargo',
            options={'verbose_name': 'Nível do Cargo', 'verbose_name_plural': 'Níveis do Cargo'},
        ),
        migrations.AlterModelOptions(
            name='origemcapital',
            options={'verbose_name': 'Origem do Capital', 'verbose_name_plural': ' Origem do Capital'},
        ),
        migrations.AlterField(
            model_name='core',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome*'),
        ),
        migrations.AlterField(
            model_name='dimensao',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome*'),
        ),
        migrations.AlterField(
            model_name='governanca',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome*'),
        ),
        migrations.AlterField(
            model_name='nivelcargo',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome*'),
        ),
        migrations.AlterField(
            model_name='origemcapital',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome*'),
        ),
        migrations.AlterField(
            model_name='plans',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome*'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome*'),
        ),
        migrations.AlterField(
            model_name='tipoempresa',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome*'),
        ),
    ]
