# Generated by Django 3.2.1 on 2023-03-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_geral', '0008_auto_20220331_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimensao',
            options={'verbose_name': 'Dimensão Financeira', 'verbose_name_plural': 'Dimensões Financeiras'},
        ),
    ]
