# Generated by Django 3.2.1 on 2023-11-14 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_geral', '0009_alter_dimensao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimensao',
            options={'ordering': ['id'], 'verbose_name': 'Dimensão Financeira', 'verbose_name_plural': 'Dimensões Financeiras'},
        ),
    ]
