# Generated by Django 3.2.1 on 2024-03-05 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_geral', '0010_alter_dimensao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimensao',
            options={'verbose_name': 'Dimensão Financeira', 'verbose_name_plural': 'Dimensões Financeiras'},
        ),
    ]
