# Generated by Django 5.0.4 on 2025-02-21 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_geral', '0011_alter_dimensao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimensao',
            options={'ordering': ['id'], 'verbose_name': 'Dimensão Financeira', 'verbose_name_plural': 'Dimensões Financeiras'},
        ),
    ]
