# Generated by Django 5.0.4 on 2026-04-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_geral', '0012_alter_dimensao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='value_aval',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Qtde Avaliações'),
        ),
        migrations.AlterField(
            model_name='plans',
            name='value',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Qtde Descrições'),
        ),
    ]
