# Generated by Django 5.0.4 on 2026-04-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_geral', '0013_plans_value_aval_alter_plans_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlansAvaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome*')),
                ('detail', models.CharField(blank=True, default='', max_length=255, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Qtde Avaliações')),
                ('discount', models.CharField(blank=True, default='', max_length=255, verbose_name='Cupom')),
                ('percent', models.IntegerField(blank=True, default=0, null=True, verbose_name='Percentual')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Plano Avaliaçãoo',
                'verbose_name_plural': 'Planos Avaliação',
            },
        ),
        migrations.RemoveField(
            model_name='plans',
            name='value_aval',
        ),
    ]
