# Generated by Django 5.2.14 on 2026-05-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_geral', '0014_plansavaliacao_remove_plans_value_aval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plans',
            options={'verbose_name': 'Plano Descrição', 'verbose_name_plural': 'Planos Descrição'},
        ),
    ]
